nutritionist:
    resource: "@NutritionistBundle/Resources/config/routing.yml"
    prefix:   /

customer:
    resource: "@CustomerBundle/Resources/config/routing.yml"
    prefix:   /

customs:
    resource: "@CustomsBundle/Resources/config/routing.yml"
    prefix:   /

rutas_bundle:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
