<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSf7jfoa\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSf7jfoa/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSf7jfoa.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSf7jfoa\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerSf7jfoa\appProdDebugProjectContainer([
    'container.build_hash' => 'Sf7jfoa',
    'container.build_id' => '3596c445',
    'container.build_time' => 1633032646,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSf7jfoa');
