<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSu38bri\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSu38bri/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSu38bri.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSu38bri\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSu38bri\appProdProjectContainer([
    'container.build_hash' => 'Su38bri',
    'container.build_id' => '2422b8b5',
    'container.build_time' => 1628334170,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSu38bri');
