<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH3w5ufv\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH3w5ufv/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerH3w5ufv.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerH3w5ufv\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerH3w5ufv\appProdDebugProjectContainer([
    'container.build_hash' => 'H3w5ufv',
    'container.build_id' => '0ea8afb5',
    'container.build_time' => 1633864268,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH3w5ufv');
