NutritionistBundle\Entity\Appointment:
    type: entity
    table: appointment
    id:
        idAppointment:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_appointment
            generator:
                strategy: IDENTITY
    fields:
        idNutritionist:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_nutritionist
        idCustomer:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_customer
        date:
            type: datetime
            nullable: false
        duration:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '60'
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        appointmentType:
            type: string
            nullable: false
            length: 124
            options:
                fixed: false
                default: presencial
            column: appointment_type
        appointmentLink:
            type: string
            nullable: true
            length: 124
            options:
                fixed: false
            column: appointment_link
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
