NutritionistBundle\Entity\CustomerPlans:
    type: entity
    table: customer_plans
    id:
        idCustomerPlan:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_customer_plan
            generator:
                strategy: IDENTITY
    fields:
        idCustomer:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_customer
        idPlan:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_plan
        planNotes:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        dateFrom:
            type: datetime
            nullable: false
            column: date_from
        dateTo:
            type: datetime
            nullable: false
            column: date_to
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
