NutritionistBundle\Entity\CustomerNutritionist:
    type: entity
    table: customer_nutritionist
    id:
        idCustomerNutritionist:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_customer_nutritionist
            generator:
                strategy: IDENTITY
    fields:
        idNutritionist:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_nutritionist
        idCustomer:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_customer
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
