NutritionistBundle\Entity\DiaryPages:
    type: entity
    table: diary_pages
    id:
        idDiaryPage:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_diary_page
            generator:
                strategy: IDENTITY
    fields:
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_user
        date:
            type: date
            nullable: false
        tasks:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        events:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        memosAndNotes:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: memos_and_notes
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
