NutritionistBundle\Entity\Exercise:
    type: entity
    table: exercise
    id:
        idExercise:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_exercise
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 284
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        muscles:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        dateAdd:
            type: datetime
            nullable: true
            column: date_add
    lifecycleCallbacks: {  }
