NutritionistBundle\Entity\IngredientsRecipes:
    type: entity
    table: ingredients_recipes
    id:
        idIngredientRecipe:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_ingredient_recipe
            generator:
                strategy: IDENTITY
    fields:
        idIngredient:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_ingredient
        idRecipe:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_recipe
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
