NutritionistBundle\Entity\Ingredients:
    type: entity
    table: ingredients
    id:
        idIngredient:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_ingredient
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 248
            options:
                fixed: false
        carbohydrates:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '10'
        fats:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '5'
        protein:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '7'
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
