NutritionistBundle\Entity\Meal:
    type: entity
    table: meal
    id:
        idMeal:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_meal
            generator:
                strategy: IDENTITY
    fields:
        idPlan:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_plan
        mealSort:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: meal_sort
        day:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        hour:
            type: time
            nullable: false
        meal:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        mealShoppingList:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: meal_shopping_list
        mealNotes:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: meal_notes
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
