NutritionistBundle\Entity\NutritionistReceipt:
    type: entity
    table: nutritionist_receipt
    id:
        idReceipt:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_receipt
            generator:
                strategy: IDENTITY
    fields:
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_user
        idCustomer:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_customer
        idTransaction:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_transaction
        idInvoice:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_invoice
        amount:
            type: float
            nullable: false
            precision: 10
            scale: 0
        status:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        dateAdd:
            type: datetime
            nullable: true
            column: date_add
        dateUpd:
            type: datetime
            nullable: true
            column: date_upd
    lifecycleCallbacks: {  }
