NutritionistBundle\Entity\Recipes:
    type: entity
    table: recipes
    id:
        idRecipe:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_recipe
            generator:
                strategy: IDENTITY
    fields:
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: id_user
        name:
            type: string
            nullable: false
            length: 248
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        image:
            type: string
            nullable: false
            length: 248
            options:
                fixed: false

        dateAdd:
            type: datetime
            nullable: false
            column: date_add
        dateUpd:
            type: datetime
            nullable: false
            column: date_upd
    lifecycleCallbacks: {  }
