NutritionistBundle\Entity\WeeklyPlan:
    type: entity
    table: weekly_plan
    id:
        idPlan:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_plan
            generator:
                strategy: IDENTITY
    fields:
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_user
        idTag:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_tag
        title:
            type: string
            nullable: false
            length: 284
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
