NutritionistBundle\Entity\WeeklyPlanTag:
    type: entity
    table: weekly_plan_tag
    id:
        idWeekplyPlanTag:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_weekply_plan_tag
            generator:
                strategy: IDENTITY
    fields:
        idWeeklyPlan:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_weekly_plan
        idTag:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_tag
    lifecycleCallbacks: {  }
