NutritionistBundle\Entity\Workout:
    type: entity
    table: workout
    id:
        idWorkout:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_workout
            generator:
                strategy: IDENTITY
    fields:
        idPlan:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_plan
        workoutSort:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: workout_sort
        day:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        hour:
            type: time
            nullable: false
        workout:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        workoutExercises:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: workout_exercises
        workoutNotes:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: workout_notes
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
