customs_homepage:
    path:     /home/{role}
    defaults: { _controller: CustomsBundle:Default:index }

customs_loginpage:
    path:     /login
    defaults: { _controller: CustomsBundle:Default:loginpage }
