customs_homepage:
    path:   /home
    defaults: { _controller: CustomsBundle:Default:index }

login:
    path:   /login
    defaults: { _controller: CustomsBundle:Auth:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

register:
    path:   /register
    defaults: { _controller: CustomsBundle:Auth:register }

fullloginpage:
    path: /loginpage
    defaults: { _controller: CustomsBundle:Auth:index }




