customer_news:
  path:   /news
  defaults: { _controller: CustomerBundle:Customer:news }

customer_services:
  path: /services
  defaults: { _controller: CustomerBundle:Customer:services }

customer_about:
    path: /about
    defaults: { _controller: CustomerBundle:Customer:about }

customer_event_view:
  path: /event/{id_event}
  defaults: { _controller: CustomerBundle:Customer:eventView }

customer_didactic_content_view:
  path: /didactic_content/{id_entry}
  defaults: { _controller: CustomerBundle:Customer:didactiContentView }

customer_didactic_content:
  path: /content
  defaults: { _controller: CustomerBundle:Customer:didacticContent }

customer_personal_data:
  path: /personal-data
  defaults: { _controller: CustomerBundle:Customer:personalData }

customer_diary:
  path: /diary
  defaults: { _controller: CustomerBundle:Customer:diary }

customer_calendar:
  path: /calendar
  defaults: { _controller: CustomerBundle:Customer:calendar }

customer_add_event:
  path: /add-event
  defaults: { _controller: CustomerBundle:Customer:addEvent }

customer_recipes:
  path: /recipes/{id_recipe}
  defaults: { _controller: CustomerBundle:Customer:recipes }

customer_progress:
  path: /progress
  defaults: { _controller: CustomerBundle:Customer:progress }

customer_messenger:
  path: /messenger
  defaults: { _controller: CustomerBundle:Customer:messenger }
