CustomsBundle\Entity\Category:
    type: entity
    table: category
    id:
        idCategory:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_category
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        titleSeo:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: title_seo
        descriptionShort:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: description_short
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        linkRewrite:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: link_rewrite
        dateAdd:
            type: datetime
            nullable: true
            column: date_add
        dateUpd:
            type: datetime
            nullable: true
            column: date_upd

    oneToMany:
        entries:
            targetEntity: Entry
            cascade: [ "persist" ]
            mappedBy: idCategory
    lifecycleCallbacks: {  }
