CustomsBundle\Entity\Entry:
    type: entity
    table: entry
    indexes:
        fk_entry_user:
            columns:
                - id_user
        fk_entry_category:
            columns:
                - id_category
    id:
        idEntry:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_entry
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        image:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        dateAdd:
            type: datetime
            nullable: true
            column: date_add
        dateUpd:
            type: datetime
            nullable: true
            column: date_upd
    manyToOne:
        idCategory:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_category:
                    referencedColumnName: id_category
            orphanRemoval: false
        idUser:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id_user
            orphanRemoval: false
    lifecycleCallbacks: {  }
