CustomsBundle\Entity\Message:
    type: entity
    table: message
    id:
        idMessage:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_message
            generator:
                strategy: IDENTITY
    fields:
        idUserFrom:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_user_from
        idUserTo:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_user_to
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        subject:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        messageRead:
            type: boolean
            nullable: false
            options:
                default: '0'
        dateRead:
            type: datetime
            nullable: true
            column: date_read
        dateAdd:
            type: datetime
            nullable: false
            column: date_add
    lifecycleCallbacks: {  }
