CustomsBundle\Entity\NutritionistCustomerCard:
    type: entity
    table: nutritionist_customer_card
    id:
        idCard:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_card
            generator:
                strategy: IDENTITY
    fields:
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_user
        name:
            type: string
            nullable: false
            length: 242
            options:
                fixed: false
        ncDigits:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: nc_digits
        ncLastDigits:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nc_last_digits
        ncExpMonth:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nc_exp_month
        ncExpYear:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nc_exp_year
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        brand:
            type: string
            nullable: true
            length: 24
            options:
                fixed: false
        dateAdd:
            type: datetime
            nullable: true
            column: date_add
        dateUpd:
            type: datetime
            nullable: true
            column: date_upd
    lifecycleCallbacks: {  }
