<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC2nsend\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC2nsend/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerC2nsend.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerC2nsend\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerC2nsend\appDevDebugProjectContainer([
    'container.build_hash' => 'C2nsend',
    'container.build_id' => 'e41ac876',
    'container.build_time' => 1628333660,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC2nsend');
